### ISSUE TITLE
`WasmTable.fromIPCStream` erroring on fully null column of type `Bool`

### ISSUE THREAD

**Issue by csjh** [kylebarron/arrow-wasm#58]
Hi! Thanks for making this and `parquet-wasm`, they've been super helpful.

I'm running into an issue with serialization of fully null bool columns.

Reproduction:
```js
import {
	vectorFromArray,
	Table as ArrowTable,
	Bool,
	tableToIPC
} from 'apache-arrow';
import { Table as WasmTable } from 'parquet-wasm/node/arrow1.js';

const table = new ArrowTable({ x: vectorFromArray([null, null], new Bool()) });
table.schema.fields[0].nullable = true;

// errors with `Error: Invalid argument error: Need at least 1 bytes for bitmap in buffers[0] in array of type Boolean, but got 0`
WasmTable.fromIPCStream(tableToIPC(table));
```
It doesn't seem to be a bug with `apache-arrow`'s serialization, because it also errors with `table = tableFromIPC(<bytes generated with pyarrow>)`.

Is this a bug on this side, or should I pull this upstream to `arrow-rs`?

**Comment by kylebarron** [comment]
Yeah I just tested and it works just fine with a file from pyarrow, so I expect the error is in Arrow JS

```py
import pyarrow as pa
arr = pa.BooleanArray.from_pandas([False, False], mask=[True, True], type=pa.bool_())
table = pa.table({'a': arr})
with pa.ipc.RecordBatchStreamWriter('test.arrows', table.schema) as writer:
    writer.write_table(table)
```

```js
var wasm = require('./pkg/node/arrow1')
var fs = require('fs')
var buffer = fs.readFileSync('test.arrows')
var arr = new Uint8Array(buffer)
var wasmTable = wasm.Table.fromIPCStream(arr)
wasmTable.numBatches // 1
schema = wasmTable.schema
field = schema.field(0)
field.name() // 'a'
```

**Comment by csjh** [comment]
I was using this for my pyarrow repro:
```py
import pyarrow as pa
from io import BytesIO

bools = pa.array([None, None], type=pa.bool_())
table = pa.table({'x': bools})

sink = BytesIO()
with pa.ipc.RecordBatchStreamWriter(sink, table.schema) as writer:
    writer.write_table(table)
print(list(sink.getvalue()))
```
And it throws the error, though not totally sure what the major difference between our examples is.

**Comment by csjh** [comment]
Oh wait, realizing my mistake there, I was putting them into `tableToIPC(tableFromIPC(<bytes>))` which would still hit an ArrowJS serialization bug.

**Comment by kylebarron** [comment]
Yeah the error is almost certainly in Arrow JS

**Comment by csjh** [comment]
Closing in favour of apache/arrow#39776, thanks for the help
