### ISSUE TITLE
Record batch access from table instances - probably typo

### ISSUE THREAD

**Issue by H-Plus-Time** [kylebarron/arrow-wasm#92]
It looks like both the `record_batch` and `record_batches` methods on `Table` are gated behind the 'recordBatch' feature (as opposed to 'record_batch') - that's a typo, right?

**Comment by H-Plus-Time** [comment]
I also had to prepend `crate::` to the 4 references to RecordBatch, similar to the schema method.

**Comment by kylebarron** [comment]
Yeah, that's a typo. Are you able to make a quick pr fix?

**Comment by H-Plus-Time** [comment]
Yup, easy

**Comment by kylebarron** [comment]
Closed by #93
